export const SOLVE_PROBLEM_INITIAL = 'SOLVE_PROBLEM_INITIAL';
export const SOLVE_PROBLEM_START = 'SOLVE_PROBLEM_START';
export const SOLVE_PROBLEM_SUCCESS = 'SOLVE_PROBLEM_SUCCESS';
export const SOLVE_PROBLEM_FAILED = 'SOLVE_PROBLEM_FAILED';
