export const SOLVE_PROBLEM_INITIAL = 'SOLVE_PROBLEM_INITIAL';
export const SOLVE_PROBLEM_START = 'SOLVE_PROBLEM_START';
export const SOLVE_PROBLEM_SUCCESS = 'SOLVE_PROBLEM_SUCCESS';
export const SOLVE_PROBLEM_FAILED = 'SOLVE_PROBLEM_FAILED';

export const GET_INITIAL_STATE_INITIAL = 'GET_INITIAL_STATE_INITIAL';
export const GET_INITIAL_STATE_START = 'GET_INITIAL_STATE_START';
// export const GET_INITIAL_STATE_SUCCESS = 'GET_INITIAL_STATE_SUCCESS';
// export const GET_INITIAL_STATE_FAILED = 'GET_INITIAL_STATE_FAILED';
// export const GET_CLIENTS_AND_FARMERS_INITIAL = 'GET_CLIENTS_AND_FARMERS_INITIAL';
// export const GET_CLIENTS_AND_FARMERS_START = 'GET_CLIENTS_AND_FARMERS_START';
export const GET_CLIENTS_AND_FARMERS_SUCCESS = 'GET_CLIENTS_AND_FARMERS_SUCCESS';
export const GET_CLIENTS_AND_FARMERS_FAILED = 'GET_CLIENTS_AND_FARMERS_FAILED';
